"""add accses token

Revision ID: c531bdf4113a
Revises: 4a7b64c950d7
Create Date: 2023-01-15 13:50:23.007793

"""
from alembic import op
import sqlalchemy as sa

from fastapi_users_db_sqlalchemy import generics

# revision identifiers, used by Alembic.
revision = 'c531bdf4113a'
down_revision = '4a7b64c950d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accesstoken', sa.Column('token', sa.String(length=43),
                                 nullable=False),
        sa.Column('created_at',
                  generics.TIMESTAMPAware(timezone=True),
                  nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('token'))
    op.create_index(op.f('ix_accesstoken_created_at'),
                    'accesstoken', ['created_at'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accesstoken_created_at'), table_name='accesstoken')
    op.drop_table('accesstoken')
    # ### end Alembic commands ###
