version: '3.9'

services:
  postgres:
    image: postgres
    env_file:
      - ./.env/database.dev.env
    volumes:
      - postgres_dev_data:/var/lib/posgresql/data
    ports:
      - 5432:5432
  api:
    depends_on:
      - postgres
    env_file:
      - ./.env/api.dev.env
    build: 
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
  nginx:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80


volumes:
  postgres_dev_data:
