# Generated by Django 4.1.5 on 2023-01-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenteduser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='extenteduser',
            name='settings',
            field=models.JSONField(blank=True),
        ),
    ]
