# Generated by Django 4.1.5 on 2023-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_extenteduser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenteduser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extenteduser',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
