# Generated by Django 4.1.5 on 2023-01-11 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_extenteduser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenteduser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='path to user avatar'),
        ),
        migrations.AlterField(
            model_name='extenteduser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date, when user was created'),
        ),
        migrations.AlterField(
            model_name='extenteduser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='extenteduser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='password hash'),
        ),
        migrations.AlterField(
            model_name='extenteduser',
            name='settings',
            field=models.JSONField(blank=True, null=True, verbose_name='user srrings, which stored like json'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date, when theme was created'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='fulle theme description, will not be shown at search'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='theme short description, will be shown at search'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=255, verbose_name='theme title, will be shown at search'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user, which saved this theme'),
        ),
    ]
