FROM python:3.10.9-alpine3.17

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./requirements/base.txt .
COPY ./requirements/dev.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r dev.txt

COPY . /app

CMD ["uvicorn",  "--reload",  "--host", "0.0.0.0",  "--port", "8000", "src.main:api"]
